using MKL, TensorKit, JLD2, FiniteLattices, TimerOutputs, KrylovKit, SerializedElementArrays
import LinearAlgebra: BLAS, cross, diagm
import Statistics: std

include("Globals.jl")
include("init.jl")
include("tools/threading.jl")

include("tools/TensorKit.jl")

include("TensorWrapper/AbstractType.jl")
include("Graph/node.jl")
include("Graph/edge.jl")
include("Graph/layermap.jl")
include("TensorWrapper/AbstractTensor.jl")
include("TensorWrapper/AbstractEnvironmentTensor.jl")
include("Environment/AbstractEnvironment.jl")
include("Interaction/operator.jl")
include("Observables/operator.jl")
include("Interaction/tunnel.jl")
include("Graph/dag.jl")
include("MPS/AbstractMPS.jl")
include("MPO/AbstractMPO.jl")
include("Hamiltonian/AbstractHamiltonian.jl")

include("ProcessControl/truncations.jl")
include("ProcessControl/AbstractType.jl")
include("ProcessControl/algorithm.jl")
include("ProcessControl/direction.jl")
include("ProcessControl/information.jl")
include("ProcessControl/scheme.jl")
include("ProcessControl/structure.jl")

# include("Graph/optimize.jl")
include("Graph/bipartite.jl")
include("Graph/iterator.jl")
include("Graph/myhill.jl")
# include("Graph/operations.jl")

include("Defaults.jl")

include("TensorWrapper/TensorWrapper.jl")
include("TensorWrapper/canonicalize.jl")
include("TensorWrapper/method.jl")
include("TensorWrapper/operations.jl")

# include("MPS/contract.jl")
include("MPS/methods.jl")
include("MPS/operations.jl")

# include("MPO/contract.jl")
include("MPO/methods.jl")
include("MPO/operations.jl")

include("Environment/operations.jl")
include("Environment/push/wrapper.jl")
include("Environment/push/push3.jl")
include("Environment/push/push4.jl")

include("Environment/contract/push/mps dense.jl")
include("Environment/contract/push/mps sparse.jl")
include("Environment/contract/push/mpo dense.jl")
include("Environment/contract/push/mpo sparse.jl")
include("Environment/contract/push/mpo sparse 4.jl")

include("Environment/contract/composite/mpo sparse 3.jl")
include("Environment/contract/composite/mpo dense 3.jl")
include("Environment/contract/composite/mpo sparse 1.jl")
include("Environment/contract/composite/mps dense 1.jl")
include("Environment/contract/composite/mps dense 3.jl")
include("Environment/contract/composite/mps sparse 3.jl")
include("Environment/contract/composite/mps sparse 1.jl")

include("Environment/contract/join/wrapper.jl")
include("Environment/contract/join/sparse.jl")
include("Environment/contract/join/composite 1.jl")
include("Environment/contract/join/composite 3.jl")

include("Environment/contract/retain/left.jl")
include("Environment/contract/retain/right.jl")

include("Hamiltonian/densify.jl")
# include("Hamiltonian/contract.jl")
include("Hamiltonian/contract/action0.jl")
include("Hamiltonian/contract/action1.jl")
include("Hamiltonian/contract/action2.jl")
include("Hamiltonian/action/sparse.jl")
include("Hamiltonian/action/mps dense.jl")
include("Hamiltonian/action/mpo dense.jl")
include("Hamiltonian/action_cache/cache.jl")
include("Hamiltonian/action_cache/mps dense.jl")
include("Hamiltonian/action_cache/mpo dense.jl")
include("Hamiltonian/action_cache/mps sparse.jl")
include("Hamiltonian/action_cache/mpo sparse.jl")

include("Interaction/graph.jl")
include("Interaction/addIntr.jl")
include("Interaction/automata.jl")
include("Interaction/algebra.jl")

include("Observables/weight.jl")
include("Observables/graph.jl")
include("Observables/addObs.jl")
include("Observables/update.jl")
include("Observables/tools.jl")
include("Observables/stack.jl")
include("Observables/calObs.jl")
include("Observables/instance.jl")

# include("tools/algebra.jl")
# include("tools/geometry.jl")
# include("tools/tools.jl")
# include("tools/lattice.jl")
include("tools/entropy.jl")
include("tools/swap.jl")
include("tools/KrylovKit.jl")
include("tools/show.jl")

include("Algebra/inner.jl")
include("Algebra/mul/wrapper.jl")
include("Algebra/mul/core.jl")
include("Algebra/mul/step1.jl")
include("Algebra/mul/step2.jl")
include("Algebra/axpby/wrapper.jl")
include("Algebra/axpby/core.jl")
include("Algebra/axpby/step2.jl")
include("Algebra/operations.jl")
# include("Algebra/contract/scalar.jl")


include("Algorithm/DMRG/wrapper.jl")
include("Algorithm/DMRG/core.jl")
include("Algorithm/DMRG/step1.jl")
include("Algorithm/DMRG/step2.jl")
# include("Algorithm/DMRG/utils.jl")

include("Algorithm/TDVP/wrapper.jl")
include("Algorithm/TDVP/core.jl")
include("Algorithm/TDVP/step1.jl")
include("Algorithm/TDVP/step2.jl")
# include("Algorithm/TDVP/utils.jl")

include("Algorithm/CBE/wrapper.jl")
include("Algorithm/CBE/CBE3.jl")
# include("Algorithm/CBE/CBE3-3.jl")
include("Algorithm/CBE/svd.jl")
include("Algorithm/CBE/orthogonalize.jl")
include("Algorithm/CBE/splice.jl")
# include("Algorithm/CBE/contract/composite.jl")
# include("Algorithm/CBE/contract/join.jl")
# include("Algorithm/CBE/contract/projection.jl")
# include("Algorithm/CBE/contract/retain.jl")
# include("Algorithm/CBE/contract/splice.jl")
include("Algorithm/CBE/utils.jl")
include("Algorithm/XTRG.jl")
include("Algorithm/SETTN.jl")

include("Algorithm/TaSK/environment.jl")
include("Algorithm/TaSK/operations.jl")
include("Algorithm/TaSK/algebra.jl")
include("Algorithm/TaSK/orthogonalize.jl")
include("Algorithm/TaSK/action.jl")
include("Algorithm/TaSK/lanczos.jl")

include("Projector/environment.jl")
include("Projector/tensor.jl")

include("LocalSpace/Fermion/symmetric.jl")
include("LocalSpace/Fermion/trivial.jl")
include("LocalSpace/Spin/symmetric.jl")
include("LocalSpace/Spin/trivial.jl")

